volumes:
  postgres-data:
    external: true

services:
  postgres:
      image: postgres:14.5-bullseye
      volumes:
          - postgres-data:/var/lib/postgresql/data
      environment:
          POSTGRES_PASSWORD: pixelpals
          POSTGRES_USER: pixelpals
          POSTGRES_DB: pixeldb
      ports:
          - 15432:5432

  fastapi:
    environment:
      DATABASE_URL: postgresql://pixelpals:pixelpals@postgres/pixeldb
      CORS_HOST: http://localhost:3000
      SIGNING_KEY: 4c9af740f86e0e2f32be8c786a8a14584b565c07f93c1cd622600479c05f85f9
    build:
      context: api
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./api:/app
  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      REACT_APP_API_HOST: ${REACT_APP_API_HOST}
